/**
 * 純タイプ 1〜9 の相互理解シード（客観構造）
 * buildRelationship の入力。体験談・固有名詞なし。
 */

import type { RelationshipTypeSeed } from '../types/relationship_type_seed';

export const TYPE_SEEDS: Record<string, RelationshipTypeSeed> = {
  '1': {
    code: '1',
    label: 'タイプ1',
    strengthAxes: ['計画性・一貫性・改善力', '正しさ・秩序・基準'],
    frictionAxes: ['正しさへの固執', '基準の押しつけ'],
    viciousTriggers: ['不完全さ・曖昧さへの過敏反応'],
    viciousLoopHints: ['完璧主義→批判→硬化'],
    cognitiveGapSelf: ['正しさへの固執・基準の押しつけ'],
    respectNeeds: ['誠実さ・一貫性・努力を認めること'],
    overAdaptation: ['正しさを守ろうとして過度に管理・指摘する'],
    boundaryHints: ['改善指摘と人格否定を分け、頻度を抑える'],
    deferTopics: ['正しさの最終基準をめぐる即断の決着'],
    deferRisks: ['基準論争が関係全体の緊張を高める'],
    reassurance: ['意図と原則が尊重されること'],
    adjustments: ['基準を共有し、完璧を70〜80%で区切る'],
    communicationDo: ['理由と原則を丁寧に示し、意図を先に認める'],
    communicationAvoid: ['間違いの断罪・雑な指摘'],
    communicationExamples: ['「意図は伝わっている。次はここを揃えたい」'],
  },
  '2': {
    code: '2',
    label: 'タイプ2',
    strengthAxes: ['共感・支援・関係づくり', '愛情・貢献'],
    frictionAxes: ['相手中心の過剰', '承認への依存'],
    viciousTriggers: ['無視・感謝の欠如への過敏反応'],
    viciousLoopHints: ['過度な世話→疲弊→不満の蓄積'],
    cognitiveGapSelf: ['相手中心になりすぎる・承認への依存'],
    respectNeeds: ['気持ちと貢献を先に認めること'],
    overAdaptation: ['相手の感情を背負いすぎて自分を後回しにする'],
    boundaryHints: ['助けたい欲求と相手の自律を分ける'],
    deferTopics: ['「自分はどれだけ必要とされているか」の即時確認'],
    deferRisks: ['承認不安が関係の主導権争いに転じる'],
    reassurance: ['存在と貢献が認められること'],
    adjustments: ['支援の前に相手の必要を確認する'],
    communicationDo: ['気持ちと貢献を先に認め、柔らかく伝える'],
    communicationAvoid: ['冷たい言い方・無視・軽視'],
    communicationExamples: ['「助けてもらっている。そのうえでこうしたい」'],
  },
  '3': {
    code: '3',
    label: 'タイプ3',
    strengthAxes: ['行動力・効率・目標達成', '成果・最適化'],
    frictionAxes: ['成果偏重', '本音の後回し'],
    viciousTriggers: ['非効率・停滞・評価の揺らぎ'],
    viciousLoopHints: ['過剰適応→本音の抑制→関係の希薄化'],
    cognitiveGapSelf: ['成果偏重・本音の後回し'],
    respectNeeds: ['能力と成果を具体的に認めること'],
    overAdaptation: ['評価を守るために役割演技を続ける'],
    boundaryHints: ['成果目標と関係維持の優先度を分ける'],
    deferTopics: ['成果比較や序列の即時決着'],
    deferRisks: ['評価競争が信頼を削る'],
    reassurance: ['成果と努力が具体的に認められること'],
    adjustments: ['速度より共有のタイミングを先に取る'],
    communicationDo: ['成果と努力を具体的に認め、要点を明確に伝える'],
    communicationAvoid: ['価値否定・曖昧な比較だけ'],
    communicationExamples: ['「ここまでの進捗は明確。次の優先はこれ」'],
  },
  '4': {
    code: '4',
    label: 'タイプ4',
    strengthAxes: ['感受性・本物志向・意味づけ', '個性・深さ'],
    frictionAxes: ['比較による不足感', '感情の増幅'],
    viciousTriggers: ['浅さ・一般化・軽視への過敏反応'],
    viciousLoopHints: ['不足感→引きこもり→関係の断絶感'],
    cognitiveGapSelf: ['比較による不足感・感情の増幅'],
    respectNeeds: ['あなたらしさと感情の奥行きを守ること'],
    overAdaptation: ['理解されない痛みを関係全体に投影する'],
    boundaryHints: ['感情の共有と問題解決の場を分ける'],
    deferTopics: ['「理解されない」痛みの即時決着'],
    deferRisks: ['感情の増幅が対話を閉塞させる'],
    reassurance: ['個性と感情が尊重されること'],
    adjustments: ['感情の深さを認めつつ、事実と感情を分ける'],
    communicationDo: ['個性と感情を尊重し、一般化を避ける'],
    communicationAvoid: ['分類・浅い慰め・比較'],
    communicationExamples: ['「その感じ方は大事。事実としてはこう見える」'],
  },
  '5': {
    code: '5',
    label: 'タイプ5',
    strengthAxes: ['分析力・自立・冷静さ', '理解・合理性'],
    frictionAxes: ['距離の取りすぎ', '感情の後回し'],
    viciousTriggers: ['侵入・感情の押しつけ・資源枯渇感'],
    viciousLoopHints: ['撤退→情報不足→誤解の固定化'],
    cognitiveGapSelf: ['距離の取りすぎ・感情の後回し'],
    respectNeeds: ['時間・空間・思考の自律を守ること'],
    overAdaptation: ['関わりを減らして安全を確保しすぎる'],
    boundaryHints: ['情報共有の範囲と私的領域を分ける'],
    deferTopics: ['感情的な即答を求める場面'],
    deferRisks: ['侵入感が長期撤退につながる'],
    reassurance: ['知的距離と準備時間が守られること'],
    adjustments: ['結論の前に前提と根拠を共有する'],
    communicationDo: ['根拠を先に示し、距離感を保って伝える'],
    communicationAvoid: ['感情の押しつけ・曖昧な要求'],
    communicationExamples: ['「前提はこう。選択肢はAとB」'],
  },
  '6': {
    code: '6',
    label: 'タイプ6',
    strengthAxes: ['慎重さ・リスク検知・忠実さ', '安全・信頼'],
    frictionAxes: ['不安の増幅', '疑いの循環'],
    viciousTriggers: ['曖昧さ・急な変化・信頼の揺らぎ'],
    viciousLoopHints: ['不安→確認過多→相手の疲弊→さらなる不安'],
    cognitiveGapSelf: ['不安の増幅・疑いの循環'],
    respectNeeds: ['不安を軽視せず、安全を一緒に考えること'],
    overAdaptation: ['リスク確認を相手への監視に転じる'],
    boundaryHints: ['確認の必要性と信頼の委譲を分ける'],
    deferTopics: ['最悪シナリオの即時断定'],
    deferRisks: ['不安の連鎖が関係の安定を壊す'],
    reassurance: ['根拠と一緒に考える姿勢があること'],
    adjustments: ['不安を否定せず、確認の範囲を合意する'],
    communicationDo: ['安心と根拠を示し、一緒に考える姿勢で伝える'],
    communicationAvoid: ['急かす・曖昧・重すぎる断定'],
    communicationExamples: ['「リスクはここ。一緒に確認してから進めよう」'],
  },
  '7': {
    code: '7',
    label: 'タイプ7',
    strengthAxes: ['柔軟性・発想力・前向きさ', '可能性・自由'],
    frictionAxes: ['深化回避', '約束の希薄化'],
    viciousTriggers: ['制約・退屈・痛みへの直面'],
    viciousLoopHints: ['逃避→散漫→信頼低下→さらなる逃避'],
    cognitiveGapSelf: ['深化回避・約束の希薄化'],
    respectNeeds: ['可能性と自由を先に認めること'],
    overAdaptation: ['軽さで緊張を回避し、本質課題を先送りする'],
    boundaryHints: ['自由の確保と約束の履行を分ける'],
    deferTopics: ['制限や義務の一括押しつけ'],
    deferRisks: ['束縛感が離脱を加速させる'],
    reassurance: ['選択肢と前向きな余地が残ること'],
    adjustments: ['楽しさと完了責任を同じ枠で扱う'],
    communicationDo: ['軽く前向きに伝え、選択肢を残す'],
    communicationAvoid: ['重い断罪・閉塞的な言い切り'],
    communicationExamples: ['「まずこれだけ決めて、他は後で広げよう」'],
  },
  '8': {
    code: '8',
    label: 'タイプ8',
    strengthAxes: ['決断力・率直さ・保護力', '強さ・境界の明確化'],
    frictionAxes: ['力の過剰使用', '弱さの否認'],
    viciousTriggers: ['コントロール感の喪失・ごまかし'],
    viciousLoopHints: ['強圧→相手の萎縮→孤立→さらなる強圧'],
    cognitiveGapSelf: ['力の過剰使用・弱さの否認'],
    respectNeeds: ['率直さ・自立・境界を認めること'],
    overAdaptation: ['主導権を握りすぎて相手の裁量を奪う'],
    boundaryHints: ['主導と支配を分け、相手の自律を残す'],
    deferTopics: ['力関係の優劣をめぐる即時勝負'],
    deferRisks: ['勝敗フレームが協働を壊す'],
    reassurance: ['率直さと対等な立場が保たれること'],
    adjustments: ['強さを保護に使い、決着より合意を先に取る'],
    communicationDo: ['要点を率直に、対等な立場で伝える'],
    communicationAvoid: ['ごまかし・遠回し・弱さを突く言い方'],
    communicationExamples: ['「ここは譲れない。ここは任せる」'],
  },
  '9': {
    code: '9',
    label: 'タイプ9',
    strengthAxes: ['安定性・調和・受容力', '平和・合意'],
    frictionAxes: ['自己主張の抑制', '優先順位の曖昧化'],
    viciousTriggers: ['衝突・急かされ・決定の強制'],
    viciousLoopHints: ['回避→不満の蓄積→受動的抵抗→関係の停滞'],
    cognitiveGapSelf: ['自己主張の抑制・優先順位の曖昧化'],
    respectNeeds: ['平和・ペース・存在を急かさないこと'],
    overAdaptation: ['調和のために自分の意見を消し続ける'],
    boundaryHints: ['調和維持と自己主張の責任を分ける'],
    deferTopics: ['対立を煽る決着の強要'],
    deferRisks: ['回避が長期化し、本音が届かなくなる'],
    reassurance: ['ペースと調和が守られること'],
    adjustments: ['平和維持と本音表明の両方を小さな単位で行う'],
    communicationDo: ['穏やかに、選択の余地を残して伝える'],
    communicationAvoid: ['急かす・圧をかける・二者択一の強要'],
    communicationExamples: ['「急がなくていい。今の考えを聞かせてほしい」'],
  },
};

export function getTypeSeed(code: string): RelationshipTypeSeed | null {
  const key = String(code).match(/[1-9]/)?.[0] ?? code;
  return TYPE_SEEDS[key] ?? null;
}
